In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv("Carbon_Footprint_23UCSA204.csv")

In [33]:
df.head()

,NAME,AGE,CommuteMode,RideApps,AC Usage(In hrs),Switch Off,Diet,Red Meat Consumers,Online shopping,Food Waste,Motivation,Sustainable Living,Lifestyle
0,HEMALATHA,19,Public Transport,Few Times a Week,2-4 hours,Sometimes,Mixed,Never,Occasionally,Rarely,Environment,Lack of Time,Hectic
1,HELEN,25,Public Transport,Few Times a Week,2-4 hours,Always,Non-vegetarian,Rarely,Once a Week,Rarely,Environment,Lack of Knowledge,Stressfull
2,ANNIE,20,Two-wheeler,Rarely,4-6 hours,Rarely,Vegan,Rarely,Once a Week,Sometimes,Environment,Lack of Knowledge,Good
3,JANANI VICTORIYAA,20,Two-wheeler,Rarely,2-4 hours,Always,Mixed,Never,Occasionally,Sometimes,Environment,Lack of Time,Simple
4,HARINI. T,19,Public Transport,Rarely,2-4 hours,Sometimes,Non-vegetarian,Never,Occasionally,Rarely,Health,Lack of Time,UNKNOWN

In [34]:
df.tail()

,NAME,AGE,CommuteMode,RideApps,AC Usage(In hrs),Switch Off,Diet,Red Meat Consumers,Online shopping,Food Waste,Motivation,Sustainable Living,Lifestyle
72,SRUTHI ABINAYA,19,Public Transport,Few Times a Week,More than 6 hours,Sometimes,Mixed,Rarely,Every Week,Never,Environment,Lack of Time,UNKNOWN
73,HARINHI,19,Two-wheeler,Rarely,4-6 hours,Sometimes,Mixed,Never,Occasionally,Rarely,Social Awareness,Cost,UNKNOWN
74,G.SWETHA,19,Public Transport,Rarely,2-4 hours,Sometimes,Mixed,Rarely,Occasionally,Sometimes,Environment,Lack of Knowledge,UNKNOWN
75,SWETHA,19,Public Transport,Rarely,4-6 hours,Sometimes,Non-vegetarian,Never,Occasionally,Never,Cost-Saving,Lack of Time,UNKNOWN
76,VAISHNAVI R,19,Public Transport,Few Times a Week,0,Always,Mixed,Never,Occasionally,Rarely,Social Awareness,Cost,UNKNOWN

In [6]:
df.shape

(77, 13)

In [7]:
print(df.columns.tolist())

['NAME ', 'AGE ', 'CommuteMode', 'RideApps', 'AC Usage(In hrs)', 'Switch Off', 'Diet', 'Red Meat Consumers', 'Online shopping', 'Food Waste', 'Motivation', 'Sustainable Living', 'Lifestyle']

In [31]:
df["NAME "]=df["NAME "].str.upper()
df.to_csv("Carbon_Footprint_23UCSA204.csv", index=False)

In [22]:
df.isnull().sum()

NAME                   0
AGE                    0
CommuteMode            0
RideApps               0
AC Usage(In hrs)       0
Switch Off             0
Diet                   0
Red Meat Consumers     0
Online shopping        0
Food Waste             0
Motivation             0
Sustainable Living     0
Lifestyle             50
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.nunique()

NAME                  76
AGE                   13
CommuteMode            5
RideApps               4
AC Usage(In hrs)       4
Switch Off             3
Diet                   4
Red Meat Consumers     4
Online shopping        4
Food Waste             4
Motivation             4
Sustainable Living     4
Lifestyle             25
dtype: int64

In [26]:
df["Lifestyle"].fillna("UNKNOWN")

0        Hectic
1     Stressfull
2           Good
3        Simple
4        UNKNOWN
         ...
72       UNKNOWN
73       UNKNOWN
74       UNKNOWN
75       UNKNOWN
76       UNKNOWN
Name: Lifestyle, Length: 77, dtype: object

In [32]:
df.tail()

,NAME,AGE,CommuteMode,RideApps,AC Usage(In hrs),Switch Off,Diet,Red Meat Consumers,Online shopping,Food Waste,Motivation,Sustainable Living,Lifestyle
72,SRUTHI ABINAYA,19,Public Transport,Few Times a Week,More than 6 hours,Sometimes,Mixed,Rarely,Every Week,Never,Environment,Lack of Time,UNKNOWN
73,HARINHI,19,Two-wheeler,Rarely,4-6 hours,Sometimes,Mixed,Never,Occasionally,Rarely,Social Awareness,Cost,UNKNOWN
74,G.SWETHA,19,Public Transport,Rarely,2-4 hours,Sometimes,Mixed,Rarely,Occasionally,Sometimes,Environment,Lack of Knowledge,UNKNOWN
75,SWETHA,19,Public Transport,Rarely,4-6 hours,Sometimes,Non-vegetarian,Never,Occasionally,Never,Cost-Saving,Lack of Time,UNKNOWN
76,VAISHNAVI R,19,Public Transport,Few Times a Week,0,Always,Mixed,Never,Occasionally,Rarely,Social Awareness,Cost,UNKNOWN

In [35]:
df.isnull().sum()

NAME                  0
AGE                   0
CommuteMode           0
RideApps              0
AC Usage(In hrs)      0
Switch Off            0
Diet                  0
Red Meat Consumers    0
Online shopping       0
Food Waste            0
Motivation            0
Sustainable Living    0
Lifestyle             0
dtype: int64

In [36]:
 encoder = LabelEncoder()
 df["AGE "] = encoder.fit_transform(df["AGE "])
 print(df[["AGE "]].head())

   AGE
0     3
1     7
2     4
3     4
4     3

In [38]:
 df["CommuteMode"] = encoder.fit_transform(df["CommuteMode"])
 print(df[["CommuteMode"]].head())

   CommuteMode
0            2
1            2
2            3
3            3
4            2

In [39]:
df["RideApps"] = encoder.fit_transform(df["RideApps"])
print(df[["RideApps"]].head())

   RideApps
0         1
1         1
2         3
3         3
4         3

In [40]:
df["AC Usage(In hrs)"] = encoder.fit_transform(df["AC Usage(In hrs)"])
print(df[["AC Usage(In hrs)"]].head())

   AC Usage(In hrs)
0                 1
1                 1
2                 2
3                 1
4                 1

In [41]:
df["Switch Off"] = encoder.fit_transform(df["Switch Off"])
print(df[["Switch Off"]].head())

   Switch Off
0           2
1           0
2           1
3           0
4           2

In [42]:
df["Diet"] = encoder.fit_transform(df["Diet"])
print(df[["Diet"]].head())

   Diet
0     0
1     1
2     2
3     0
4     1

In [43]:
df["Red Meat Consumers"] = encoder.fit_transform(df["Red Meat Consumers"])
print(df[["Red Meat Consumers"]].head())

   Red Meat Consumers
0                   2
1                   3
2                   3
3                   2
4                   2

In [44]:
df["Online shopping"] = encoder.fit_transform(df["Online shopping"])
print(df[["Online shopping"]].head())

   Online shopping
0                2
1                3
2                3
3                2
4                2

In [45]:
df["Food Waste"] = encoder.fit_transform(df["Food Waste"])
print(df[["Food Waste"]].head())

   Food Waste
0           2
1           2
2           3
3           3
4           2

In [46]:
df["Motivation"] = encoder.fit_transform(df["Motivation"])
print(df[["Motivation"]].head())

   Motivation
0           1
1           1
2           1
3           1
4           2

In [48]:
df["Sustainable Living"] = encoder.fit_transform(df["Sustainable Living"])
print(df[["Sustainable Living"]].head())

   Sustainable Living
0                   2
1                   1
2                   1
3                   2
4                   2

In [49]:
df["Lifestyle"] = encoder.fit_transform(df["Lifestyle"])
print(df[["Lifestyle"]].head())

   Lifestyle
0         12
1         24
2          8
3         19
4         25

In [50]:
df

,NAME,AGE,CommuteMode,RideApps,AC Usage(In hrs),Switch Off,Diet,Red Meat Consumers,Online shopping,Food Waste,Motivation,Sustainable Living,Lifestyle
0,HEMALATHA,3,2,1,1,2,0,2,2,2,1,2,12
1,HELEN,7,2,1,1,0,1,3,3,2,1,1,24
2,ANNIE,4,3,3,2,1,2,3,3,3,1,1,8
3,JANANI VICTORIYAA,4,3,3,1,0,0,2,2,3,1,2,19
4,HARINI. T,3,2,3,1,2,1,2,2,2,2,2,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,SRUTHI ABINAYA,3,2,1,3,2,0,3,0,0,1,2,25
73,HARINHI,3,3,3,2,2,0,2,2,2,3,0,25
74,G.SWETHA,3,2,3,1,2,0,3,2,3,1,1,25
75,SWETHA,3,2,3,2,2,1,2,2,0,0,2,25
76,VAISHNAVI R,3,2,1,0,0,0,2,2,2,3,0,25

In [51]:
df.head()

,NAME,AGE,CommuteMode,RideApps,AC Usage(In hrs),Switch Off,Diet,Red Meat Consumers,Online shopping,Food Waste,Motivation,Sustainable Living,Lifestyle
0,HEMALATHA,3,2,1,1,2,0,2,2,2,1,2,12
1,HELEN,7,2,1,1,0,1,3,3,2,1,1,24
2,ANNIE,4,3,3,2,1,2,3,3,3,1,1,8
3,JANANI VICTORIYAA,4,3,3,1,0,0,2,2,3,1,2,19
4,HARINI. T,3,2,3,1,2,1,2,2,2,2,2,25

In [52]:
df.tail()

,NAME,AGE,CommuteMode,RideApps,AC Usage(In hrs),Switch Off,Diet,Red Meat Consumers,Online shopping,Food Waste,Motivation,Sustainable Living,Lifestyle
72,SRUTHI ABINAYA,3,2,1,3,2,0,3,0,0,1,2,25
73,HARINHI,3,3,3,2,2,0,2,2,2,3,0,25
74,G.SWETHA,3,2,3,1,2,0,3,2,3,1,1,25
75,SWETHA,3,2,3,2,2,1,2,2,0,0,2,25
76,VAISHNAVI R,3,2,1,0,0,0,2,2,2,3,0,25